name: Scheduled update of schema files

on:
  schedule:
    - cron: '0 2 * * 3'   # Runs every Wednesday at 2:00 AM UTC
  workflow_dispatch:      # Allow manual trigger as well

jobs:
  update-schema-files-esr-mv2:
    if: ${{ always() }}
    uses: ./.github/workflows/update.yml
    with:
      release: esr
      branch: esr-mv2
      manifestVersion: 2

  update-schema-files-esr-mv3:
    if: ${{ always() }}
    needs: update-schema-files-esr-mv2
    uses: ./.github/workflows/update.yml
    with:
      release: esr
      branch: esr-mv3
      manifestVersion: 3

  update-schema-files-release-mv2:
    if: ${{ always() }}
    needs: update-schema-files-esr-mv3
    uses: ./.github/workflows/update.yml
    with:
      release: release
      branch: release-mv2
      manifestVersion: 2

  update-schema-files-release-mv3:
    if: ${{ always() }}
    needs: update-schema-files-release-mv2
    uses: ./.github/workflows/update.yml
    with:
      release: release
      branch: release-mv3
      manifestVersion: 3

  update-schema-files-beta-mv2:
    if: ${{ always() }}
    needs: update-schema-files-release-mv3
    uses: ./.github/workflows/update.yml
    with:
      release: beta
      branch: beta-mv2
      manifestVersion: 2

  update-schema-files-beta-mv3:
    if: ${{ always() }}
    needs: update-schema-files-beta-mv2
    uses: ./.github/workflows/update.yml
    with:
      release: beta
      branch: beta-mv3
      manifestVersion: 3
